name: imodel
description:
version: 0.1.2
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: any
  true_core:
    git:
      url: https://github.com/TrueCollaboration/package.true_core.dart.git
  ientity:
    git:
      url: https://github.com/TrueCollaboration/package.ientity.dart.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
